# Generated by Django 5.1.6 on 2025-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], max_length=10)),
                ('crust', models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('thick', 'Thick'), ('stuffed_cheese', 'Stuffed (cheese)'), ('stuffed_tomato', 'Stuffed (tomato sauce)'), ('gluten_free', 'Gluten Free')], max_length=20)),
                ('sauce', models.CharField(choices=[('tomato', 'Tomato'), ('bbq', 'BBQ'), ('alfredo', 'Alfredo')], max_length=20)),
                ('cheese', models.CharField(choices=[('mozzarella', 'Mozzarella'), ('vegan', 'Vegan'), ('low_fat', 'Low Fat')], max_length=20)),
                ('toppings', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
