# Generated by Django 5.1.6 on 2025-02-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_topping_remove_pizza_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('mozzarella', 'Mozzarella'), ('vegan', 'Vegan'), ('low_fat', 'Low fat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('thick', 'Thick'), ('stuffed_cheese', 'Stuffed (cheese)'), ('stuffed_tomato', 'Stuffed (tomato sauce)'), ('gluten_free', 'Gluten-free')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('tomato', 'Tomato'), ('bbq', 'BBQ'), ('alfredo', 'Alfredo'), ('garlic', 'Tomato and garlic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('mini', 'Mini'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
