# Generated by Django 5.1.6 on 2025-02-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('eircode', models.CharField(blank=True, max_length=7, null=True)),
                ('card_number', models.CharField(max_length=19)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=5)),
            ],
        ),
    ]
